<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("tags", "Сотрудники, Помощь, Ответы на вопросы, Поддержка");
$APPLICATION->SetPageProperty("description", "Результатом усилий сотрудников производственной компании «#ZAVOD_NAME#», являются сертифицированные готовые бетонные смеси, доставка и подача товарного бетона в любых условиях, в нужном объеме и точно в срок.");
//$APPLICATION->SetPageProperty("keywords", "сотрудники, московский бетон, задать вопрос, телефон, консультация");
$APPLICATION->SetPageProperty("title", "Сотрудники «#ZAVOD_NAME_RP#»");
$APPLICATION->SetTitle("Сотрудники завода «#SELECT_3#»");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"staff", 
	array(
		"IBLOCK_TYPE" => "aspro_max_content",
		"IBLOCK_ID" => "16",
		"NEWS_COUNT" => "120",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/company/staff/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "100000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "EMAIL",
			1 => "SOCIAL_VK",
			2 => "SOCIAL_ODN",
			3 => "SOCIAL_FB",
			4 => "SOCIAL_MAIL",
			5 => "SOCIAL_TW",
			6 => "SOCIAL_SKYPE",
			7 => "SOCIAL_INST",
			8 => "SOCIAL_GOOGLE",
			9 => "SOCIAL_BITRIX",
			10 => "VIDEO",
			11 => "POST",
			12 => "LINK_NEWS",
			13 => "LINK_REVIEWS",
			14 => "LINK_PARTNERS",
			15 => "SEND_MESSAGE_BUTTON",
			16 => "LINK_PROJECTS",
			17 => "LINK_BLOG",
			18 => "PHONE",
			19 => "LINK_SERVICES",
			20 => "PHOTOS",
			21 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "EMAIL",
			1 => "SOCIAL_VK",
			2 => "SOCIAL_ODN",
			3 => "SOCIAL_FB",
			4 => "SOCIAL_MAIL",
			5 => "SOCIAL_TW",
			6 => "SOCIAL_SKYPE",
			7 => "SOCIAL_INST",
			8 => "SOCIAL_GOOGLE",
			9 => "SOCIAL_BITRIX",
			10 => "VIDEO",
			11 => "POST",
			12 => "LINK_NEWS",
			13 => "LINK_REVIEWS",
			14 => "LINK_PARTNERS",
			15 => "SEND_MESSAGE_BUTTON",
			16 => "LINK_PROJECTS",
			17 => "LINK_BLOG",
			18 => "PHONE",
			19 => "LINK_SERVICES",
			20 => "PHOTOS",
			21 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"VIEW_TYPE" => "table",
		"SHOW_TABS" => "N",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"COUNT_IN_LINE" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"USE_REVIEW" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"IMAGE_POSITION" => "left",
		"COMPONENT_TEMPLATE" => "staff",
		"SET_LAST_MODIFIED" => "N",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"STRICT_SECTION_CHECK" => "N",
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"FILE_404" => "",
		"SIDE_LEFT_BLOCK" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK" => "FROM_MODULE",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"T_DOCS" => "",
		"T_VIDEO" => "",
		"IBLOCK_LINK_NEWS_ID" => "20",
		"IBLOCK_LINK_SERVICES_ID" => "22",
		"IBLOCK_LINK_TIZERS_ID" => "3",
		"IBLOCK_LINK_REVIEWS_ID" => "19",
		"IBLOCK_LINK_STAFF_ID" => "16",
		"IBLOCK_LINK_VACANCY_ID" => "2",
		"IBLOCK_LINK_BLOG_ID" => "17",
		"IBLOCK_LINK_PROJECTS_ID" => "15",
		"IBLOCK_LINK_BRANDS_ID" => "30",
		"IBLOCK_LINK_LANDINGS_ID" => "",
		"BLOCK_SERVICES_NAME" => "Услуги лаборатории",
		"BLOCK_NEWS_NAME" => "Новости",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_REVIEWS_NAME" => "Отзывы о бетонном заводе в #REGION_NAME_DECLINE_PP#",
		"BLOCK_STAFF_NAME" => "Сотрудники",
		"BLOCK_VACANCY_NAME" => "Вакансии",
		"BLOCK_PROJECTS_NAME" => "Проекты",
		"BLOCK_BRANDS_NAME" => "Бренды",
		"BLOCK_BLOG_NAME" => "Статьи",
		"BLOCK_LANDINGS_NAME" => "Коллекции",
		"IBLOCK_LINK_PARTNERS_ID" => "23",
		"BLOCK_PARTNERS_NAME" => "Наши клиенты",
		"USE_SHARE" => "N",
		"GALLERY_TYPE" => "small",
		"STAFF_TYPE_DETAIL" => "list",
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"DETAIL_BLOCKS_ALL_ORDER" => "tizers,desc,char,docs,reviews,projects,gallery,services,news,vacancy,blog,staff,comments,brands,partners,video,goods,landings,form_order,sale",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"VK_TITLE" => "Вконтакте",
		"DETAIL_VK_API_ID" => "API_ID",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>
<?php $APPLICATION->IncludeFile("/include/seo_meta.php");?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>